/***********************************************************************/
/*                                                                     */
/*  FILE        :TIME.c                                                */
/*  DATE        :Thu, Jun 23, 2022                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3694F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  


#include "lcd.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

#define WAIT_LOOP_FOR_1MSEC   3500

void waitTimeMS();

void main(void)
{

	int h=0;
    int m=0;
    int s=0;

    InitLcd();
	
	while(1){
		//waitTimeMS(10);
		s++;
        waitTimeMS(1000);
	    if(s == 60){
	      	s = 0;
	       	m++;
       	}	
	    if(m == 60){
	      	m = 0;
       		h++;
       	}
       	if(h == 24){
	      	h = 0;
        }
		
    	LcdXY(1,1);
		LcdPuts("h:");	
		putLCDNumber(4,(unsigned int)h);
		LcdPuts("m:");	
		putLCDNumber(4,(unsigned int)m);
		
    	LcdXY(1,2);		
		LcdPuts("s:");	
		putLCDNumber(4,(unsigned int)s);
	}
}

void waitTimeMS(unsigned int mSec)
{
	unsigned int loopCount1,loopCount2;
    
	for(loopCount1=0; loopCount1<mSec; loopCount1++){
	    for(loopCount2=0; loopCount2 < WAIT_LOOP_FOR_1MSEC; loopCount2++);   
    }
    
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
